language: cpp


matrix:
  include:
    - os: linux
      dist: xenial

    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4
      
  allow_failures:
    - os: windows



script: 
    - cd cpp
    - cmake ./
    - cmake --build ./ --target dummy_sample
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp ../lib/mac/libnyumaya.dylib /usr/local/lib && ./dummy_sample ../models/Hotword/marvin_small_0.3.tflite  ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dummy_sample ../models/Hotword/marvin_small_0.3.tflite  ; fi

