language: cpp


matrix:
  include:
    - os: linux
      dist: xenial
      apt:
          packages:
            - python3
            - pip3
          
    - os: osx
      osx_image: xcode10.1
      addons:
          homebrew:
            packages:
              - python3
              
    - os: osx
      osx_image: xcode9.4
      addons:
          homebrew:
            packages:
              - python3
      
  allow_failures:
    - os: windows



install:
  - pip install --user pydub
  - pip3 install --user pydub

script: 
  - cd cpp
  - cmake ./
  - cmake --build ./ --target dummy_sample
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp ../lib/mac/libnyumaya.dylib /usr/local/lib && ./dummy_sample ../models/Hotword/marvin_small_0.3.tflite  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dummy_sample ../models/Hotword/marvin_small_0.3.tflite  ; fi

  - cd ../../
  - pwd
  - git clone https://github.com/yodakohl/nyumaya_audio_testdata.git
  - cd nyumaya_audio_testdata
  - pwd
  - unzip nyumaya_marvin_test_0_1.zip
  - cd $TRAVIS_BUILD_DIR/python
  - bash test_mini.sh


