language: cpp


matrix:
  include:
    - os: linux
      dist: xenial

    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4
      
  allow_failures:
    - os: windows



script: 
    - cd cpp
    - cmake ./
    - cmake --build ./ --target dummy_sample
    - ./dummy_sample ../models/Hotword/marvin_small_0.3.tflite 

